version: '3.4'

services:
  acc:
    image: malekabadi/cloud-project:latest
    ports:
      - 2082:2082
    depends_on:
      - docker-mysql
    restart: unless-stopped
    links:
      - docker-mysql:mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2082/account/heartbeat"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
#      placement:
#        preferences:
#        - spread: node.labels.nodes
  mysql-db:
    image: mysql
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cloud
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost","-proot" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - mysql-db-data:/data/db

volumes:
  mysql-db-data: