version: '3.4'

services:
  acc:
    image: malekabadi/cloud-project:latest
    expose:
      - 2082
    ports:
      - 2082:2082
    depends_on:
      - docker-mysql
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/cloud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    #    links:
#      - "docker-mysql:mysql"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2082/account/heartbeat"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
#      placement:
#        preferences:
#        - spread: node.labels.nodes
  docker-mysql:
    image: mysql
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cloud
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost","-proot" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - mysql-db-data:/data/db

volumes:
  mysql-db-data: